# Generated by Django 3.2.7 on 2021-11-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('done_for_today', models.CharField(max_length=100)),
                ('important', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('is_closed', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
