# Generated by Django 3.2.7 on 2021-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211112_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomeet',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
